from __future__ import annotations

from pathlib import Path

from .constants import EXIT_USAGE
from .errors import OracleError
from .io import digest_json

DOSBOX_PROFILE = {
    "schema": "amipro-oracle-dosbox-config-v1",
    "machine": "svga_s3",
    "memory_mb": 16,
    "cpu_core": "normal",
    "cycles": 12000,
    "capture_timeout_ms": 2000,
    "window_resolution": "800x600",
}


def _container_path(value: str) -> str:
    path = Path(value)
    if not path.is_absolute() or "\n" in value or "\r" in value or '"' in value:
        raise OracleError(f"unsafe container path: {value!r}", exit_code=EXIT_USAGE)
    return value


def dosbox_config(
    *,
    runtime_path: str = "/oracle/job/runtime",
    capture_path: str = "/oracle/job/capture",
) -> str:
    runtime = _container_path(runtime_path)
    capture = _container_path(capture_path)
    return f"""# Generated by amipro-oracle; do not edit.
[sdl]
fullscreen=false
output=surface
windowresolution={DOSBOX_PROFILE['window_resolution']}
autolock=true
clip_mouse_button=none
waitonerror=false
priority=normal,normal

[dosbox]
machine={DOSBOX_PROFILE['machine']}
memsize={DOSBOX_PROFILE['memory_mb']}
captures={capture}
synchronize time=false

[render]
aspect=true
scaler=none

[cpu]
core={DOSBOX_PROFILE['cpu_core']}
cycles=fixed {DOSBOX_PROFILE['cycles']}

[mixer]
nosound=true

[serial]
serial1=disabled
serial2=disabled
serial3=disabled
serial4=disabled

[dos]
startcmd=false
network redirector=false
automount=false
automountall=false
automount drive directories=false
dos clipboard device enable=disabled
dos clipboard api=false

[parallel]
parallel1=file timeout:{DOSBOX_PROFILE['capture_timeout_ms']}

[ipx]
ipx=false

[ne2000]
ne2000=false
backend=none

[autoexec]
@ECHO OFF
MOUNT C "{runtime}"
C:
"""


def dosbox_config_digest() -> str:
    return digest_json({"profile": DOSBOX_PROFILE, "text": dosbox_config()})
